WINDOW_WIDTH=50
WINDOW_HEIGHT=25

SOLIDER_IMG=solider.png

GRASS_IMG=grass.png
GRASS_WIDTH=3
GRASS_HEIGHT=1

FLAG_IMG=flag.png
FLAG_WIDTH=3
FLAG_HEIGHT=4
FLAG_X = WINDOW_WIDTH / 2 - (FLAG_WIDTH / 2)
FLAG_Y = WINDOW_HEIGHT * 0.8
FLAG_MIDBOTTOM_X = FLAG_X + FLAG_WIDTH / 2
FLAG_MIDBOTTOM_Y = FLAG_Y + FLAG_HEIGHT
11122