WINDOW_WIDTH=500
WINDOW_HEIGHT=250
ROW=25
COL=50


SOLIDER_IMG=solider.png
SOLIDER_START_X=0
SOLIDER_START_Y=0

GRASS_IMG=grass.png
GRASS_WIDTH=30
GRASS_HEIGHT=10

FLAG_IMG=flag.png
FLAG_WIDTH=30
FLAG_HEIGHT=40
#מיקום הדגל
FLAG_X = 500
FLAG_Y = 250


BACKGROUND_COLOR = (0, 153, 0)
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

