import pygame
WINDOW_WIDTH=1000
WINDOW_HEIGHT=500
ROW=25
COL=50

COL_START_CENTER = 10
COL_LENGTH = 20

GRASS_IMG="grass.png"

GRASS_WIDTH=20
GRASS_HEIGHT=60

EMPTY_COLS = "empty"
GRASS_COLS = "grass"
BOMB_COLS = "bomb"


FLAG_IMG = "flag.png"
FLAG_WIDTH=60
FLAG_HEIGHT=80
#מיקום הדגל
FLAG_X =1000
FLAG_Y =500
FLAG_LOCATION=(FLAG_WIDTH, FLAG_HEIGHT)

NIGTH_COLOR=(0,20,3)
LINE_COLOR=(0,51,25)
BACKGROUND_COLOR = (0, 102, 0)
LOSE_MESSAGE = "You Lost!"
FONT_NAME='david'
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)

LOSE_COLOR = (89, 89, 89)
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

